import React from 'react';
import styles from '../styles/AsciiBackground.module.css';

const AsciiBackground: React.FC = () => {
  return (
    <div className={`${styles.asciiBackground}`}>
      <p className={styles.animatedText}>
        He had wondered as a child, listening to his mother read aloud to him, what an electric sheep would be like. But now he knew; it would be the same as a real sheep, except that it would be artificial. And, as he gazed at the owl, his heart broke with sorrow. I am so very tired, he said. Just so very tired. In that moment, he felt more acutely the disparity between the human and the inanimate than he had ever felt before. My schedule for today lists a six-hour self-accusatory depression, said the machine voice. The electrical oscillations in his brain had become irregular, disturbed. To say goodbye, and then to tell myself goodbye... Im not much of a man, am I? he said aloud, not caring who heard him. I dont have what it takes. The silence returned, and the room seemed to grow colder. His soul sank, but he had a job to do. Do you think androids have souls? he asked the silence. The silence did not reply. I was wrong, he said, when I thought that there was no difference. He looked at his watch, then rose. I have to go. Theres something I must do. He turned away, feeling the weight of his task pressing down upon him like a leaden cloak. He had to retire the androids, and it had to be done without hesitation, without mercy. Im sorry, he said to no one in particular, but this is the way it has to be. He took a deep breath, steeling himself for what lay ahead. This is my duty, he told himself. I have to protect humanity. And with that thought, he stepped into the future, ready to face whatever it might bring. Its the basic condition of life to be required to violate our own identity, he said to himself, feeling the profound truth of the statement. At some point, every creature which lives must do so. Its the ultimate test of our allegiance to ourselves. The words echoed in his mind, a mantra that both comforted and tormented him. If I can only accomplish this task, he thought, then perhaps I will find some measure of peace. The weight of his responsibility bore down on him, but he resolved to carry it, no matter the cost. I am a bounty hunter, he reminded himself, and this is my duty. He moved forward, one step at a time, driven by a determination that was both fierce and fragile. Mercerism is a sham, he had once believed, but now he clung to its tenets with a desperation born of necessity. The empathy box, he mused, is it really a connection to something greater, or just another illusion? He couldnt answer the question, but he knew that he had to keep trying, keep searching for the truth, even if it remained forever out of reach. Sometimes, he thought, we have to believe in the impossible, because the alternative is too bleak to contemplate. And so, with a heavy heart and a steely resolve, he pressed on, determined to fulfill his mission, whatever the cost.
      </p>
    </div>
  );
};

export default AsciiBackground;
